version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=qlpo
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    # expose:
    #   - 3306
    networks:
      - qlpo_network

  backend:
    build:
      context: ../../NODEJS
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST_MYSQL=db
      - DB_PORT_MYSQL=3306
      # - DB_USER_MYSQL=root
      # - DB_PASSWORD_MYSQL=yes
      # DB_HOST_MYSQL=host.docker.internal
    ports:
      - 8086:8086
    depends_on:
      - db
    expose:
      - 8086
    networks:
      - qlpo_network

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../../REACT/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - qlpo_network
networks:
  qlpo_network:
