version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=qlpo
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
   